package it.eng.idsa.clearinghouse.client.utils;

/**
 * @author Antonio Scatoloni on 09/12/2020
 **/

public class TimezoneRemover {

    public static String removeTimezoneFromIssued(String objectJson) {
        // 2020-08-27T09:30:41.962UTC -> 2020-08-27T09:30:41.962Z
        // The first one is generated by jackson problems with Timezone!!!
        String[] lines = objectJson.split(System.lineSeparator());
        if (null != lines && lines.length > 0) {
            for (String line : lines) {
                if (line.contains("ids:issued") && line.contains("UTC")) {
                    String originalLine = line;
                    line = line.replaceAll("UTC", "Z");
                    objectJson = objectJson.replace(originalLine, line);
                }
            }
        }
        return objectJson;
    }
}
